-- SQL Schema for ElectroManager Supabase Tables

-- 1. Profiles (Ensure role is included)
-- This table usually already exists if auth is set up correctly with triggers
-- ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role text DEFAULT 'customer';

-- 2. Products
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    category TEXT,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Suppliers
CREATE TABLE IF NOT EXISTS public.suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    contact_person TEXT,
    email TEXT,
    phone TEXT,
    categories TEXT,
    address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Orders (Basic schema for revenue tracking)
CREATE TABLE IF NOT EXISTS public.orders (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_id uuid REFERENCES auth.users(id),
    total_amount DECIMAL(10, 2),
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policies for Products (Read for all, Write for Admin)
CREATE POLICY "Allow public read access" ON public.products FOR SELECT USING (true);
-- Update with actual admin check logic if needed: 
-- CREATE POLICY "Allow admin crud" ON public.products FOR ALL USING (auth.jwt() ->> 'email' LIKE '%admin%');

-- Simple policy for demonstration (Replace with proper role-based checks)
CREATE POLICY "Enable all for everyone (development)" ON public.products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for everyone (development)" ON public.suppliers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for everyone (development)" ON public.profiles FOR ALL USING (true) WITH CHECK (true);
